## CircleCI configuration
version: 2
jobs:
  java8:
    docker:
      - image: circleci/openjdk:8
      
    environment: 
      - POP_DEBUG: true
      
    steps:
      - checkout
      - restore_cache:
          keys:
            - pop-cache-{{ checksum "build.gradle" }}
            - pop-cache-
              
      - run: 
            name: Build POP-Java
            command: ./gradlew --no-daemon clean fatJar

      - run: 
            name: Test POP-Java
            command: ./gradlew --no-daemon test
      
      - save_cache:
          key: pop-cache-{{ checksum "build.gradle" }}
          when: always
          paths:
            - ~/.gradle
      
      - store_test_results:
          path: ~/project/build/test-results/
      - store_artifacts:
          path: ~/project/build/popjava.jar
          
  java9:
    docker:
      - image: circleci/openjdk:9
      
    environment: 
      - POP_DEBUG: true
      
    steps:
      - checkout
      - restore_cache:
          keys:
            - pop-cache-{{ checksum "build.gradle" }}
            - pop-cache-
              
      - run: 
            name: Build POP-Java
            command: ./gradlew --no-daemon clean fatJar

      - run: 
            name: Test POP-Java
            command: ./gradlew --no-daemon test
      
      - save_cache:
          key: pop-cache-{{ checksum "build.gradle" }}
          when: always
          paths:
            - ~/.gradle
      
      - store_test_results:
          path: ~/project/build/test-results/
      - store_artifacts:
          path: ~/project/build/popjava.jar
          
workflows:
  version: 2
  build_8-9:
    jobs:
      - java8
      - java9

